### ISSUE TITLE
Fix the prisma error in console in dev mode.

### ISSUE THREAD

**Issue by ShahbaazX786** [ShahbaazX786/tracker.io#15]
Error: PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `unknown`).

This might be a dev mode only problem but better be sure.

**Comment by avi-l** [comment]
I believe the problem stems from here:
```
 "use client";

import LatestIssues from "@/components/LatestIssues";

export default function Home() {
  return (
    <>
      {/* <h1>Bismillah</h1> */}
      <LatestIssues />
    </>
  )
}
```

the 'use client' is forcing LatestIssues  to be client instead of server. I commented this use client out in my branch for dark mode and it got rid of the error. 
Addressed in https://github.com/ShahbaazX786/tracker.io/pull/16

**Comment by ShahbaazX786** [comment]
This issue is now resolved by @avi-l contributions.
Hence marking this as close.
